image: node:latest

stages:
  - build
  - test
  - deploy
  
cache:
    paths:
        - node_modules/

build:
  stage: build
  script:
    - npm install --progress=false
    - npm run build
    
unit tests:
  stage: test
  script:
    - npm install --progress=false
    - npm run test:unit
    
end to end tests:
  stage: test
  script:
    - npm install --progress=false
    - npm run test:e2e
    
lint:
    stage: test
    script:
    - npm install --progress=false
    - npm run lint
    
deploy_production:
  stage: deploy
  only:
    - master
  script:
    - npm install -g firebase-tools
    - yarn install
    - yarn build
    - firebase deploy -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token $FIREBASE_DEPLOY_KEY