image: node:latest

stages:
  - build
  - test
  - deploy
  
cache:
    paths:
        - node_modules/
        
before_script:
    - npm install --progress=false

build:
  stage: build
  script:
    - npm run build
    
unit tests:
  stage: test
  script:
    - npm run test:unit
  allow_failure: true
    
end to end tests:
  stage: test
  script:
    - npm run test:e2e
  allow_failure: true
    
lint:
  stage: test
  script:
    - npm run lint
  allow_failure: true

deploy_production:
  stage: deploy
  only:
    - master
  script:
    - npm install -g firebase-tools
    - npm run build
    - firebase deploy -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token $FIREBASE_DEPLOY_KEY